### ISSUE TITLE
Getting java.lang.NullPointerException

### ISSUE THREAD

**Issue by sisodiakaran** [jexp/batch-import#105]
```
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name fulltext|exact rels_index.csv ....]
Using: Importer batch.properties graph.db nodes.csv rels.csv

Using Existing Configuration File

Importing 18852 Nodes took 0 seconds 

Total import time: 4 seconds 
Exception in thread "main" java.lang.NullPointerException
    at org.neo4j.batchimport.importer.RelType.update(RelType.java:9)
    at org.neo4j.batchimport.Importer.importRelationships(Importer.java:153)
    at org.neo4j.batchimport.Importer.doImport(Importer.java:232)
    at org.neo4j.batchimport.Importer.main(Importer.java:83)
```

**Comment by sisodiakaran** [comment]
Figured out the issue. This was due to empty relation type.
