### ISSUE TITLE
Index lookup in relationship file throws NumberFormatException

### ISSUE THREAD

**Issue by jmozah** [jexp/batch-import#108]
I tried using the example given in legacy indexing.
Nodes are getting created.. but the relationship stage throws a error

[Current time:2014-11-13 14:50:50.063][Compile Time:Importer $ batch-import-2.1.0 $ 17/10/2014 11:35:26]
Node Import: [1] Property[7] Node[4] Relationship[0] Label[0] Disk[0 mb, 0 mb/sec] FreeMem[3614 mb]
[2014-11-13 14:50:52.845]   Node file [nodes.csv] imported in 2 secs - [Property[7] Node[4] Relationship[0] Label[0]]
[2014-11-13 14:50:52.845]Node Import complete in 2 secs - [Property[7] Node[4] Relationship[0] Label[0]]java.lang.NumberFormatException: For input string: "Michael"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:441)
    at java.lang.Long.parseLong(Long.java:483)
    at org.neo4j.batchimport.importer.structs.AbstractDataBuffer.getLong(AbstractDataBuffer.java:159)
    at org.neo4j.unsafe.batchinsert.BatchInserterImplNew.accumulateNodeCount(BatchInserterImplNew.java:743)
    at org.neo4j.batchimport.importer.stages.NodeStatsAccumulatorStage$2.execute(NodeStatsAccumulatorStage.java:24)
    at org.neo4j.batchimport.importer.stages.ImportWorker.processData(ImportWorker.java:144)
    at org.neo4j.batchimport.importer.stages.ImportWorker.run(ImportWorker.java:196)
Invoke stage method failed:ImportNode_Stage1:[Error in accumulateNodeCount - For input string: "Michael"]:1

**Comment by jexp** [comment]
You use the wrong project

Please redownload this projects binaries and try again

Von meinem iPhone gesendet
