### ISSUE TITLE
NumberFormatException when importing relationships file

### ISSUE THREAD

**Issue by rene75** [jexp/batch-import#111]
Using Version 2.1 of the Neo4j (CSV) Batch Importer on a MacBook, this is what I get when I try importing these (https://www.dropbox.com/sh/y7oswfzf8ey5ie1/AAAt22FElwuZyDBN4YR6FVdna?dl=0) 3 files:

sh import.sh test.db brands_head.csv,products_head.csv products2brands_head.csv
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name fulltext|exact rels_index.csv ....]
Using: Importer batch.properties test.db brands_head.csv,products_head.csv products2brands_head.csv

Using Existing Configuration File

Importing 71 Nodes took 0 seconds 

Importing 58 Nodes took 0 seconds 

Total import time: 1 seconds 
Exception in thread "main" java.lang.NumberFormatException: For input string: "[Ljava.lang.String;@1a691aca"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:441)
    at java.lang.Long.parseLong(Long.java:483)
    at org.neo4j.batchimport.Importer.id(Importer.java:213)
    at org.neo4j.batchimport.Importer.id(Importer.java:181)
    at org.neo4j.batchimport.Importer.importRelationships(Importer.java:147)
    at org.neo4j.batchimport.Importer.doImport(Importer.java:232)
    at org.neo4j.batchimport.Importer.main(Importer.java:83)

These CSV files are being generated on the very same machine by a perl script, so I doubt that it has to do with some windows-line-ending-problem. What's it that I'm missing? Any help greatly appreciated.
- rene

**Comment by rene75** [comment]
This problem was probably because I downloaded from the master branch. Tried again using the 2.1 branch and the problem was gone. (I'm getting other error messages now, but that's a different story / thread).
