### ISSUE TITLE
Error running batch_importer_22

### ISSUE THREAD

**Issue by ppope** [jexp/batch-import#115]
Greetings,

I am attempting to use the `batch_importer_22` binary as described in the README.

I obtain the following error:

```
vagrant@vagrant-ubuntu-trusty-64:~/batch_importer_22$ bash import.sh test.db nodes.csv rels.csv
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name
 fulltext|exact rels_index.csv ....]
Using: Importer batch.properties test.db nodes.csv rels.csv

Writing Configuration File to batch.properties
Exception in thread "main" java.lang.NoClassDefFoundError: org/neo4j/io/fs/FileSystemAbstraction
        at org.neo4j.batchimport.Importer.createBatchInserter(Importer.java:64)
        at org.neo4j.batchimport.Importer.<init>(Importer.java:40)
        at org.neo4j.batchimport.Importer.main(Importer.java:82)
Caused by: java.lang.ClassNotFoundException: org.neo4j.io.fs.FileSystemAbstraction
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 3 more
```

My system specs:
Ubuntu 14.04.2 LTS
neo4j-community-2.2.1
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)

**Comment by jexp** [comment]
Sorry for that, should be fixed if you redownload.

Please report back.

**Comment by ppope** [comment]
Thanks for the expedient reply.

The above error is solved, however I obtain a missing file error now:

```
vagrant@vagrant-ubuntu-trusty-64:~/batch_importer_22$ ./import.sh test.db nodes.csv rels.csv
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name
 fulltext|exact rels_index.csv ....]
Using: Importer batch.properties test.db nodes.csv rels.csv

Writing Configuration File to batch.properties
File nodes.csv does not exist, can not be read or is not a file.
File rels.csv does not exist, can not be read or is not a file.

Total import time: 1 seconds 
```

Files `nodes.csv` and `rels.csv` are not included with the zipped binary, but I noted that they exist in the `batch-import` repo under `/samples`. Copying them over to the binary directory obtains a different error:

```
vagrant@vagrant-ubuntu-trusty-64:~/batch_importer_22$ ./import.sh test.db nodes.csv rels.csv
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name fulltext|exact rels_index.csv ....]
Using: Importer batch.properties test.db nodes.csv rels.csv

Writing Configuration File to batch.properties

Total import time: 1 seconds 
Exception in thread "main" java.lang.IllegalStateException: Index users not configured.
        at org.neo4j.batchimport.Importer.importNodes(Importer.java:108)
        at org.neo4j.batchimport.Importer.doImport(Importer.java:228)
        at org.neo4j.batchimport.Importer.main(Importer.java:83)
```

**Comment by jexp** [comment]
yes the example uses an indexed field which you have to configure in batch.properties or in the command line. See the `sample/batch.properties`
