### ISSUE TITLE
How can I know which line is it crashing on?

### ISSUE THREAD

**Issue by eugenem** [jexp/batch-import#117]
```
Import graph
Using Existing Configuration File
..
Total import time: 3 seconds 
Exception in thread "main" java.lang.NumberFormatException: For input string: "Male"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.valueOf(Integer.java:582)
        at org.neo4j.batchimport.importer.Type$2.convert(Type.java:13)
        at org.neo4j.batchimport.importer.RowData.split(RowData.java:86)
        at org.neo4j.batchimport.importer.RowData.updateMap(RowData.java:92)
        at org.neo4j.batchimport.Importer.importNodes(Importer.java:93)
        at org.neo4j.batchimport.Importer.main(Importer.java:57)
```

I've got few hundred thousand rows and a lot of them have Male values

**Comment by jexp** [comment]
You probably want to use the new import tool which comes with Neo4j 2.2
Which has more reporting, see http://neo4j.com/docs/stable/import-tool.html
