### ISSUE TITLE
Direct buffer memory error

### ISSUE THREAD

**Issue by sheymann** [jexp/batch-import#28]
Hi,

I try to build on Netbeans, but have this error:

> Tests in error: 
>  testFillBuffer(org.neo4j.batchimport.handlers.RelationshipUpdateCacheTest): Direct buffer memory

java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:633)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:98)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:288)
    at org.neo4j.batchimport.handlers.RelationshipUpdateCache.createBuffers(RelationshipUpdateCache.java:72)
    at org.neo4j.batchimport.handlers.RelationshipUpdateCache.<init>(RelationshipUpdateCache.java:56)
    at org.neo4j.batchimport.handlers.RelationshipUpdateCacheTest.testFillBuffer(RelationshipUpdateCacheTest.java:37)

my netbeans.conf file has "-J-Xms512m -J-XX:PermSize=512m -J-Xmx1400m -J-XX:MaxPermSize=1400m"

Any idea of what's going on?

**Comment by jexp** [comment]
That test acquires 20G of memory, just @Ignore it.

**Comment by sheymann** [comment]
okay thanks!
