### ISSUE TITLE
Start/End Rel sort and creating relationship properties

### ISSUE THREAD

**Issue by seawolff** [jexp/batch-import#33]
In the rels csv what is the significance of the start/end fields. I'm having a hard time understanding what the significance is and how to use it for my current data.

Here is an example of my two csvs:

user.tsv:

```
id  username    email     full_name 
1   wolff   wolff@wolff.io  Wolff 
2   test    test@test.com Test
```

user_rels.tsv:

```
id  type          lang        date_joined           
1   staff       en-us      2010-09-22 11:58:10  
2           en-us      2010-09-29 12:00:09  
```

I think my core misunderstanding is how the relationship is created from the row in user.tsv to the properties in user_rels.tsv.

When I run a batch-import I get the following error:

```
java -server -Dfile.encoding=UTF-8 -Xmx4G -jar db/batch-import-jar-with-dependencies.jar db/neo4j-development db/csv/Users.tsv db/csv/Users_rels.tsv
Using Existing Configuration File
Importing 116416 Nodes took 1 seconds
Total import time: 1 seconds
Exception in thread "main" java.lang.NumberFormatException: For input string: "staff"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
    at java.lang.Long.parseLong(Long.java:410)
    at java.lang.Long.parseLong(Long.java:468)
    at org.neo4j.batchimport.Importer.id(Importer.java:144)
    at org.neo4j.batchimport.Importer.importRelationships(Importer.java:108)
    at org.neo4j.batchimport.Importer.main(Importer.java:63)
```

Obviously I'm not setting up my rels file correctly. Could someone please point out my error.

Thanks.

**Comment by redapple** [comment]
Hi @seawolff 

it seems to me your `user_rels.tsv` represents properties for the users, not really relationships between users
or is there an implicit COMPANY end-node?

The first 2 columns in your rels file should represent the IDs of the start-node and end-node
(see https://github.com/jexp/batch-import#relscsv)
and the 3rd column should be the type of relationship

The subsequent columns represent additional properties of the relationship

then, **with an additional 1st node representing the company**,
and representing the relationship using "WORKS_AT",
you could write your files in this way:
`nodes.tsv`

```
id  type    name    email   full_name 
1   COMPANY ACMECorp.   contact@acme.com    ACME Corporation
2   USER    wolff   wolff@wolff.io  Wolff 
3   USER    test    test@test.com   Test
...
```

and
`rels.tsv`

```
startnode   endnode relationtype    type    lang    date_joined           
2   1   WORKS_AT    staff   en-us   2010-09-22 11:58:10
3   1   WORKS_AT        en-us   2010-09-29 12:00:09
...
```

Node 2 (user wolff) works at Node1 (ACME) as a staff member, speaks English, and joined on Sep. 22, 2010
Node 3 (user test) works at Node1 (ACME) (role in company undefined), speaks English, and joined on Sep. 29, 2010

Hope this helps.

**Comment by redapple** [comment]
Note that the "id" column in user.tsv will be used as just another property for the node, not the Node ID in Neo4J

Using `batch-import` it's the order in which the nodes appear in the nodes file that should be used as reference for the rels file

In other words, you could have:

```
id  type    name    email   full_name 
2597    COMPANY ACMECorp.   contact@acme.com    ACME Corporation
1350    USER    wolff   wolff@wolff.io  Wolff 
93754   USER    test    test@test.com   Test
```

and still define the relationships using:

```
startnode   endnode relationtype    type    lang    date_joined           
2   1   WORKS_AT    staff   en-us   2010-09-22 11:58:10
3   1   WORKS_AT        en-us   2010-09-29 12:00:09
```
