### ISSUE TITLE
Difficulty with automatic indexing

### ISSUE THREAD

**Issue by emiliefj** [jexp/batch-import#41]
I'm completely new to this, and I'm basically just trying to get the examples working. I manage to make a database just fine until I try to add auto indexing. 

I have added 

batch_import.node_index.users=exact

to the batch.properties file.

I am using the example files exactely as they are (exept without int-declaration in rels, it didn't seem to like that):

nodes.csv:
name:string:users    age works_on
Michael 37  neo4j
Selina  14
Rana    6
Selma   4

rels.csv:
start:string:users  end:string:users    type        since   counter
Michael     Selina   FATHER_OF  1998-07-10  1
Michael     Rana   FATHER_OF 2007-09-15  2
Michael     Selma   FATHER_OF 2008-05-03  3
Rana     Selma   SISTER_OF 2008-05-03  5
Selina     Rana   SISTER_OF 2007-09-15  7

This is what I get when I try:

Importing 4 Nodes took 0 seconds

Total import time: 1 seconds
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NullPointerException
        at org.neo4j.batchimport.Importer.lookup(Importer.java:100)
        at org.neo4j.batchimport.Importer.id(Importer.java:139)
        at org.neo4j.batchimport.Importer.importRelationships(Importer.java:115)

```
    at org.neo4j.batchimport.Importer.doImport(Importer.java:188)
    at org.neo4j.batchimport.Importer.main(Importer.java:74)
    ... 6 more
```

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An exception occured while executing the Java class. null

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10 seconds
[INFO] Finished at: Thu Jul 04 11:02:19 CEST 2013
[INFO] Final Memory: 28M/183M
[INFO] ------------------------------------------------------------------------

What am I doing wrong?

**Comment by jexp** [comment]
This 
start:string:users end:string:users type since counter

should be:
name:string:users name:string:users type since counter

**Comment by emiliefj** [comment]
ok, I tried changing it. It still doesent work. 

Importing 4 Nodes took 0 seconds

Total import time: 1 seconds
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NullPointerException
        at org.neo4j.batchimport.Importer.lookup(Importer.java:100)
        at org.neo4j.batchimport.Importer.id(Importer.java:139)
        at org.neo4j.batchimport.Importer.importRelationships(Importer.java:115)

```
    at org.neo4j.batchimport.Importer.doImport(Importer.java:188)
    at org.neo4j.batchimport.Importer.main(Importer.java:74)
    ... 6 more
```

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An exception occured while executing the Java class. null

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10 seconds
[INFO] Finished at: Thu Jul 04 12:31:08 CEST 2013
[INFO] Final Memory: 28M/165M
[INFO] ------------------------------------------------------------------------

Any ideas?
