### ISSUE TITLE
2.0: Windows import.bat doesn't run

### ISSUE THREAD

**Issue by craigbrett17** [jexp/batch-import#73]
I'm in a position where I need to use the 2.0 branch (I know it's not the master branch so might be unstable). 

I really like that you're providing more support to Windows users, though I'm running into an issue. When I first run the import.bat file, regardless of what arguments I give or how many, I get the following exception: 

Error occurred during initialization of VM
java.nio.charset.IllegalCharsetNameException: UTF-8 -Xmx4G -Xms4G
        at java.nio.charset.Charset.checkName(Unknown Source)
        at java.nio.charset.Charset.lookup2(Unknown Source)
        at java.nio.charset.Charset.lookup(Unknown Source)
        at java.nio.charset.Charset.defaultCharset(Unknown Source)
        at sun.nio.cs.StreamEncoder.forOutputStreamWriter(Unknown Source)
        at java.io.OutputStreamWriter.<init>(Unknown Source)
        at java.io.PrintStream.<init>(Unknown Source)
        at java.io.PrintStream.<init>(Unknown Source)
        at java.lang.System.initializeSystemClass(Unknown Source)

I started having a look through the .bat file and found by not including the EXTRA_JVM_ARGUMENTS in the line where the JAVACMD is called it works fine, kind of. I can't get it to just include the -Xmx4G -Xms4G though and I'm pretty sure when I don't include EXTRA_JVM_ARGUMENTS that the JVM just runs on it's default settings for heap. Which is making my imports ridiculously slow.

Any help/fix appreciated.

**Comment by jexp** [comment]
@craigbrett17 I just fixed that last night. Did you pull a new update of the zip-file?

Windows didn't like the double quotes around the EXTRA_JVM_ARGUMENTS, removing them helped.

**Comment by craigbrett17** [comment]
@jexp I hadn't at the time I raised this, I was a couple of days out. I have now though and it works fine off the bat. Thanks!
