### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by puredevotion** [jexp/batch-import#77]
I'm getting a NumberFormatException on a large integer:

``` java
Exception in thread "main" java.lang.NumberFormatException: For input string: "2229639275"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.valueOf(Unknown Source)
        at org.neo4j.batchimport.importer.Type$4.convert(Type.java:27)
        at org.neo4j.batchimport.importer.CsvLineData.readLine(CsvLineData.java:35)
        at org.neo4j.batchimport.importer.AbstractLineData.parse(AbstractLineData.java:139)
        at org.neo4j.batchimport.importer.AbstractLineData.processLine(AbstractLineData.java:72)
        at org.neo4j.batchimport.Importer.importNodes(Importer.java:96)
        at org.neo4j.batchimport.Importer.doImport(Importer.java:228)
        at org.neo4j.batchimport.Importer.main(Importer.java:83)
```

I have a feeling this gets returned whenever I try to import a too large file, where the number of nodes is larger than an integer can hold. 
I've tried searching my dataset for this number, but it doesn't exist. That being said, I just changed all my ints to longs to see if that has any effect...
I'll edit/post whenever I have results from that.

**Comment by jexp** [comment]
Could it be that's the last number in a row? Perhaps a line ending issue?

Ok, you should be able to find that number. And I should add a more sensible error output. That also outputs the row and column.

**Comment by puredevotion** [comment]
It looks like my integers should've been longs... 
Cheanged that, and never got that error again...
