### ISSUE TITLE
rels.csv does not exist

### ISSUE THREAD

**Issue by seenickcode** [jexp/batch-import#84]
Hello,

When I try to import a single .csv file named <somefile>.csv I get:
`File rels.csv does not exist, can not be read or is not a file.`

Kind of strange. I don't have this file mentioned in any configuration file anywhere.

I'm using the 2.0 branch of this importer.

Just curious.
Thanks

**Comment by cescalante-carecloud** [comment]
Can you post the contents of your import.sh file? 

I'm getting an error when I import just one node file and no relationship file (see below), but not with a node file and a relationship file. I tried naming my files things like ".csv" and "something.csv" and it didn't seem to make a difference. I'm not getting the `File rels.csv does not exist` error, however. 

my error message:
Importing 13775 Nodes took 1 seconds 

Total import time: 2 seconds 
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at org.neo4j.batchimport.utils.Config.toFiles(Config.java:141)
    at org.neo4j.batchimport.utils.Config.getRelsFiles(Config.java:165)
    at org.neo4j.batchimport.Importer.doImport(Importer.java:231)
    at org.neo4j.batchimport.Importer.main(Importer.java:83)
    ... 6 more
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An exception occured while executing the Java class. null

**Comment by jexp** [comment]
The shell script defaults the file name parameters (if not provided)
To nodes.csv and rels.csv

Sent from mobile device

Am 10.02.2014 um 02:16 schrieb cescalante-carecloud notifications@github.com:

**Comment by cescalante-carecloud** [comment]
Looks like I wasn't using the newer version of the import.sh file. Works as expected for me.
