### ISSUE TITLE
NoClassDefFoundError PrimitiveLongIterator

### ISSUE THREAD

**Issue by alberto1el** [jexp/batch-import#99]
I am running on a Ubuntu box and getting this error  with import.sh

```
$ ./import.sh binaria.db /var/www/neo4j/nodos.csv /var/www/neo4j/relaciones.csv
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name fulltext|exact rels_index.csv ....]
Using: Importer batch.properties binaria.db /var/www/neo4j/nodos.csv /var/www/neo4j/relaciones.csv

Using Existing Configuration File
Exception in thread "main" java.lang.NoClassDefFoundError: org/neo4j/collection/primitive/PrimitiveLongIterator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.neo4j.unsafe.impl.batchimport.staging.CoarseUnboundedProgressExecutionMonitor.poll(CoarseUnboundedProgressExecutionMonitor.java:49)
        at org.neo4j.unsafe.impl.batchimport.staging.PollingExecutionMonitor.monitor(PollingExecutionMonitor.java:48)
        at org.neo4j.unsafe.impl.batchimport.ParallellBatchImporter.executeStage(ParallellBatchImporter.java:127)
        at org.neo4j.unsafe.impl.batchimport.ParallellBatchImporter.doImport(ParallellBatchImporter.java:93)
        at org.neo4j.batchimport.Importer.doImport(Importer.java:274)
        at org.neo4j.batchimport.Importer.main(Importer.java:85)
Caused by: java.lang.ClassNotFoundException: org.neo4j.collection.primitive.PrimitiveLongIterator
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 18 more
java.lang.NullPointerException
        at org.neo4j.kernel.impl.nioneo.store.CommonAbstractStore.acquireWindow(CommonAbstractStore.java:436)
        at org.neo4j.kernel.impl.nioneo.store.NodeStore.updateRecord(NodeStore.java:197)
        at org.neo4j.kernel.impl.nioneo.store.NodeStore.updateRecord(NodeStore.java:45)
        at org.neo4j.unsafe.impl.batchimport.EntityStoreUpdaterStep.process(EntityStoreUpdaterStep.java:59)
        at org.neo4j.unsafe.impl.batchimport.EntityStoreUpdaterStep.process(EntityStoreUpdaterStep.java:38)
        at org.neo4j.unsafe.impl.batchimport.staging.ExecutorServiceStep$1.run(ExecutorServiceStep.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

I start it with 3G heap, and running openjdk-7-jdk.
Is there something I am doing wrong, I also tried running it on Windows and I am getting the same error
Is it possible that my network files are not properly build?

**Comment by alberto1el** [comment]
I found out my relations and nodes csv was malformed, I already formatted the file correctly, I hadn't identified the id columns properly
